In [2]:
import torch
from torch import autograd

#Only Tensors of floating point dtype can require gradients

c:\Users\19234\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x=torch.tensor(10.,requires_grad=True)
aphla=0.1
y=x**2+x-1
print(y)
#梯度下降法求最小值
for i in range(60):
    x=x-aphla*autograd.grad(y,x)[0]
    y=x**2+x-1#注意要更新y
    print(x)

tensor(109., grad_fn=<SubBackward0>)
tensor(7.9000, grad_fn=<SubBackward0>)
tensor(6.2200, grad_fn=<SubBackward0>)
tensor(4.8760, grad_fn=<SubBackward0>)
tensor(3.8008, grad_fn=<SubBackward0>)
tensor(2.9406, grad_fn=<SubBackward0>)
tensor(2.2525, grad_fn=<SubBackward0>)
tensor(1.7020, grad_fn=<SubBackward0>)
tensor(1.2616, grad_fn=<SubBackward0>)
tensor(0.9093, grad_fn=<SubBackward0>)
tensor(0.6274, grad_fn=<SubBackward0>)
tensor(0.4019, grad_fn=<SubBackward0>)
tensor(0.2216, grad_fn=<SubBackward0>)
tensor(0.0772, grad_fn=<SubBackward0>)
tensor(-0.0382, grad_fn=<SubBackward0>)
tensor(-0.1306, grad_fn=<SubBackward0>)
tensor(-0.2045, grad_fn=<SubBackward0>)
tensor(-0.2636, grad_fn=<SubBackward0>)
tensor(-0.3108, grad_fn=<SubBackward0>)
tensor(-0.3487, grad_fn=<SubBackward0>)
tensor(-0.3789, grad_fn=<SubBackward0>)
tensor(-0.4032, grad_fn=<SubBackward0>)
tensor(-0.4225, grad_fn=<SubBackward0>)
tensor(-0.4380, grad_fn=<SubBackward0>)
tensor(-0.4504, grad_fn=<SubBackward0>)
tensor(-0.4603, 

In [4]:
x=torch.arange(4.0,requires_grad=True)
y=torch.dot(x,x)#y=x^2

y.backward()
x.grad#y'=2x

tensor([0., 2., 4., 6.])

$$\frac{\partial }{\partial \mathbf{x}}(x_1+x_2+x_3+x_4)$$

In [5]:
x.grad.zero_()#清除导数
y=x*x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [6]:
y.sum().backward()
x.grad#返回为向量非矩阵

tensor([0., 2., 4., 6.])

In [9]:
#固定某个参数
x.grad.zero_()
u=y.detach()#不和x attach
(u*x).sum().backward()
x.grad==u#u为常数

tensor([True, True, True, True])