In [2]:
import torch
import math
x = torch.empty(5, 3)
x#不初始化

c:\Users\19234\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[-2.0984e-08,  1.0103e-42, -2.0984e-08],
        [ 1.0103e-42, -2.0984e-08,  1.0103e-42],
        [-2.0984e-08,  1.0103e-42, -2.0984e-08],
        [ 1.0103e-42, -2.0984e-08,  1.0103e-42],
        [-2.0984e-08,  1.0103e-42, -2.0984e-08]])

$n$维数组，0维为标量，1维为向量，2维为矩阵

3维图片(长宽和RGB值)4维图片批量，5维视频(加一个时间)


In [3]:
import torch
flag = torch.cuda.is_available()
print(flag)

ngpu= 1
# Decide which device we want to run on
device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
print(device)
print(torch.cuda.get_device_name(0))
print(torch.rand(3,3).cuda()) 

True
cuda:0
NVIDIA GeForce RTX 3050 Ti Laptop GPU
tensor([[0.4136, 0.2130, 0.1286],
        [0.6910, 0.4750, 0.9609],
        [0.6679, 0.4629, 0.7766]], device='cuda:0')


In [4]:
torch.cuda.device_count()

1

In [5]:
device = torch.device('cuda')

In [6]:
x = torch.zeros(5, 3, dtype=torch.long).to(device)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], device='cuda:0')

In [7]:
x = torch.rand(5, 3)
x

tensor([[0.8226, 0.1859, 0.1938],
        [0.1309, 0.3299, 0.7458],
        [0.2502, 0.0241, 0.9804],
        [0.4987, 0.6354, 0.7359],
        [0.3479, 0.7215, 0.8980]])

In [8]:
x = torch.tensor([5.5, 3])
x#初始化并赋值

tensor([5.5000, 3.0000])

In [9]:
x = torch.randn_like(x,dtype=torch.float)  
x#like,模仿创建

tensor([ 0.8391, -0.3833])

In [10]:
x.size()

torch.Size([2])

In [11]:
y = torch.rand(2)
y

tensor([0.3637, 0.5841])

In [12]:
z=torch.empty(2)
torch.add(x,y,out=z)#提供一个输出tensor 作为参数
z

tensor([1.2028, 0.2007])

In [13]:
y.add_(x)
y#in-place,带前缀'_'

tensor([1.2028, 0.2007])

In [14]:
x = torch.rand(5, 3)
x

tensor([[0.4168, 0.9244, 0.5325],
        [0.9084, 0.2524, 0.1225],
        [0.1356, 0.0992, 0.6164],
        [0.4811, 0.7342, 0.6653],
        [0.1466, 0.1257, 0.8857]])

In [15]:
x[:,1]

tensor([0.9244, 0.2524, 0.0992, 0.7342, 0.1257])

In [16]:
y=torch.randn(5,3)#正态分布
y

tensor([[-0.4564,  0.5539, -1.0607],
        [ 0.5474, -1.9281,  0.6347],
        [ 1.4794, -1.8263,  0.7036],
        [ 0.7011,  0.2873,  0.1742],
        [-1.0322,  1.3839,  0.0313]])

In [17]:
x.copy_(y)
x

tensor([[-0.4564,  0.5539, -1.0607],
        [ 0.5474, -1.9281,  0.6347],
        [ 1.4794, -1.8263,  0.7036],
        [ 0.7011,  0.2873,  0.1742],
        [-1.0322,  1.3839,  0.0313]])

In [18]:
x.view(3,5)#改维(不改变实际大小)

tensor([[-0.4564,  0.5539, -1.0607,  0.5474, -1.9281],
        [ 0.6347,  1.4794, -1.8263,  0.7036,  0.7011],
        [ 0.2873,  0.1742, -1.0322,  1.3839,  0.0313]])

In [19]:
x[1,1].item()#获取值

-1.9281198978424072

In [20]:
a=[i for i in range(1,17)]
t=torch.tensor(a).reshape(4,4)#use tensor 来创建
t

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [21]:
t1=torch.arange(1,17).reshape(4,4)
t1#use arange

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [22]:
#合并,传入一个元组
torch.cat((t,t1),dim=0),torch.cat((t,t1),dim=1)#0->行增多
#dim方向上的拼接

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),
 tensor([[ 1,  2,  3,  4,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  5,  6,  7,  8],
         [ 9, 10, 11, 12,  9, 10, 11, 12],
         [13, 14, 15, 16, 13, 14, 15, 16]]))

In [23]:
t==t1#按元素判断

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [24]:
t.sum().item()

136

In [25]:
#一个元素[1,2]
t[1,2]


tensor(7)

在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作

In [26]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [27]:
a+b#复制行和列使得维度相同

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [28]:
#切片
t[-1,:]#一行[1,:] (列为:)一列同理

tensor([13, 14, 15, 16])

In [29]:
#子区域
t[1:3,1:3]#左闭右开

tensor([[ 6,  7],
        [10, 11]])

In [30]:
#批量赋值
t[0:2,:]=1
t

tensor([[ 1,  1,  1,  1],
        [ 1,  1,  1,  1],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

\begin{bmatrix}
  \underline{1}& 1 &\underline{1}  &1 \\
  1&  1&1  & 1\\
  9& 10 &11  &12 \\
\underline{13}  & 14 & \underline{15} &16
\end{bmatrix}

In [31]:
#use::指定步长
t[::3,::2]

tensor([[ 1,  1],
        [13, 15]])

In [34]:
int(torch.rand(1)*10)#强制类型转换

7

In [33]:
before=id(t)
t+=t1
id(t)==before#原址操作，不改变id

True