In [2]:
import torch
x = torch.empty(5, 3)
x#不初始化

tensor([[2.0544e+05, 7.4829e-43, 2.0548e+05],
        [7.4829e-43, 2.0544e+05, 7.4829e-43],
        [2.0544e+05, 7.4829e-43, 2.0548e+05],
        [7.4829e-43, 2.0548e+05, 7.4829e-43],
        [2.0545e+05, 7.4829e-43, 2.0545e+05]])

In [4]:
import torch
flag = torch.cuda.is_available()
print(flag)

ngpu= 1
# Decide which device we want to run on
device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
print(device)
print(torch.cuda.get_device_name(0))
print(torch.rand(3,3).cuda()) 

True
cuda:0
GeForce GTX 750
tensor([[0.7762, 0.1105, 0.3118],
        [0.0775, 0.6379, 0.7252],
        [0.6739, 0.5455, 0.3732]], device='cuda:0')


In [6]:
torch.cuda.device_count()

1

In [ ]:
device = torch.device('cuda')

In [7]:
x = torch.zeros(5, 3, dtype=torch.long).to(device)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], device='cuda:0')

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3863, 0.9466, 0.9522],
        [0.1262, 0.8246, 0.7322],
        [0.3614, 0.1515, 0.2621],
        [0.6915, 0.7708, 0.9502],
        [0.2497, 0.0937, 0.1387]])

In [4]:
x = torch.tensor([5.5, 3])
x#初始化并赋值

tensor([5.5000, 3.0000])

In [5]:
x = torch.randn_like(x,dtype=torch.float)  
x#like,模仿创建

tensor([-0.7776,  0.8867])

In [6]:
x.size()

torch.Size([2])

In [7]:
y = torch.rand(2)
y

tensor([0.9776, 0.5695])

In [8]:
z=torch.empty(2)
torch.add(x,y,out=z)#提供一个输出tensor 作为参数
z

tensor([0.2000, 1.4562])

In [9]:
y.add_(x)
y#in-place,带前缀'_'

tensor([0.2000, 1.4562])

In [10]:
x = torch.rand(5, 3)
x

tensor([[0.6481, 0.0380, 0.0363],
        [0.7019, 0.4552, 0.5786],
        [0.0367, 0.3112, 0.3906],
        [0.4715, 0.4792, 0.3154],
        [0.5595, 0.7032, 0.1600]])

In [11]:
x[:,1]

tensor([0.0380, 0.4552, 0.3112, 0.4792, 0.7032])

In [12]:
y=torch.randn(5,3)#正态分布
y

tensor([[ 0.4929, -0.9322, -2.2454],
        [ 0.2015, -0.8741, -0.8412],
        [ 0.5035, -0.2175,  0.9903],
        [-0.0771,  0.7233,  0.6639],
        [ 0.3264, -0.1854, -0.0532]])

In [13]:
x.copy_(y)
x

tensor([[ 0.4929, -0.9322, -2.2454],
        [ 0.2015, -0.8741, -0.8412],
        [ 0.5035, -0.2175,  0.9903],
        [-0.0771,  0.7233,  0.6639],
        [ 0.3264, -0.1854, -0.0532]])

In [14]:
x.view(3,5)#改维

tensor([[ 0.4929, -0.9322, -2.2454,  0.2015, -0.8741],
        [-0.8412,  0.5035, -0.2175,  0.9903, -0.0771],
        [ 0.7233,  0.6639,  0.3264, -0.1854, -0.0532]])

In [15]:
x[1,1].item()#获取值

-0.8741397261619568