In [1]:
import torch
from torch import autograd

#Only Tensors of floating point dtype can require gradients

In [2]:
x=torch.tensor(10.,requires_grad=True)
aphla=0.1
y=x**2+x-1
print(y)
#梯度下降法求最小值
for i in range(60):
    x=x-aphla*autograd.grad(y,x)[0]
    y=x**2+x-1#注意要更新y
    print(x)

tensor(109., grad_fn=<SubBackward0>)
tensor(7.9000, grad_fn=<SubBackward0>)
tensor(6.2200, grad_fn=<SubBackward0>)
tensor(4.8760, grad_fn=<SubBackward0>)
tensor(3.8008, grad_fn=<SubBackward0>)
tensor(2.9406, grad_fn=<SubBackward0>)
tensor(2.2525, grad_fn=<SubBackward0>)
tensor(1.7020, grad_fn=<SubBackward0>)
tensor(1.2616, grad_fn=<SubBackward0>)
tensor(0.9093, grad_fn=<SubBackward0>)
tensor(0.6274, grad_fn=<SubBackward0>)
tensor(0.4019, grad_fn=<SubBackward0>)
tensor(0.2216, grad_fn=<SubBackward0>)
tensor(0.0772, grad_fn=<SubBackward0>)
tensor(-0.0382, grad_fn=<SubBackward0>)
tensor(-0.1306, grad_fn=<SubBackward0>)
tensor(-0.2045, grad_fn=<SubBackward0>)
tensor(-0.2636, grad_fn=<SubBackward0>)
tensor(-0.3108, grad_fn=<SubBackward0>)
tensor(-0.3487, grad_fn=<SubBackward0>)
tensor(-0.3789, grad_fn=<SubBackward0>)
tensor(-0.4032, grad_fn=<SubBackward0>)
tensor(-0.4225, grad_fn=<SubBackward0>)
tensor(-0.4380, grad_fn=<SubBackward0>)
tensor(-0.4504, grad_fn=<SubBackward0>)
tensor(-0.4603, 

In [3]:
x=torch.arange(4.0,requires_grad=True)
y=torch.dot(x,x)#y=x^2

y.backward()
x.grad#y'=2x

tensor([0., 2., 4., 6.])

$$\frac{\partial }{\partial \mathbf{x}}(x_1+x_2+x_3+x_4)$$

In [4]:
x.grad.zero_()#清除导数
y=x*x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [5]:
y.sum().backward()
x.grad#很少对向量求导，返回为向量非矩阵

tensor([0., 2., 4., 6.])

In [6]:
#固定某个参数
x.grad.zero_()
u=y.detach()#不和x attach
(u*x).sum().backward()
x.grad==u#u为常数

tensor([True, True, True, True])

In [10]:
import torch.optim as optim

# 1. 定义函数
def my_function(x):
    return (x - 2) ** 2

# 2. 初始化参数
x = torch.tensor([0.0], requires_grad=True)

# 3. 创建优化器
optimizer = optim.Adam([x], lr=0.01)

# 4. 迭代优化
for _ in range(1000):
    optimizer.zero_grad()  # 将优化器梯度归零

    output = my_function(x)  # 计算函数输出
    loss = output  # 损失函数为函数输出

    loss.backward()  # 反向传播

    optimizer.step()  # 更新参数

# 5. 输出最小值
print('最小值:', x.item())

最小值: 1.9999982118606567
