In [2]:
import torch
import math
x = torch.empty(5, 3)
x#不初始化

tensor([[4.7802e+26, 7.3008e-43, 4.7802e+26],
        [7.3008e-43, 4.7802e+26, 7.3008e-43],
        [4.7802e+26, 7.3008e-43, 4.7802e+26],
        [7.3008e-43, 4.7802e+26, 7.3008e-43],
        [4.7802e+26, 7.3008e-43, 4.7802e+26]])

$n$维数组，0维为标量，1维为向量，2维为矩阵

3维图片(长宽和RGB值)4维图片批量，5维视频(加一个时间)


In [3]:
import torch
flag = torch.cuda.is_available()
print(flag)

ngpu= 1
# Decide which device we want to run on
device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
print(device)
print(torch.cuda.get_device_name(0))
print(torch.rand(3,3).cuda()) 

True
cuda:0
NVIDIA GeForce RTX 3050 Ti Laptop GPU
tensor([[0.9714, 0.9532, 0.4734],
        [0.2622, 0.7284, 0.5684],
        [0.4747, 0.6658, 0.8295]], device='cuda:0')


In [4]:
torch.cuda.device_count()

1

In [5]:
device = torch.device('cuda')

In [34]:
x = torch.zeros(5, 1, dtype=torch.long).to(device)
x[0]

tensor([0], device='cuda:0')

In [7]:
x = torch.rand(5, 3)
x

tensor([[0.1727, 0.4909, 0.0768],
        [0.4012, 0.2849, 0.7349],
        [0.6170, 0.9670, 0.7720],
        [0.4325, 0.5368, 0.9603],
        [0.0980, 0.9804, 0.6363]])

In [8]:
x = torch.tensor([5.5, 3])
x#初始化并赋值

tensor([5.5000, 3.0000])

In [9]:
x = torch.randn_like(x,dtype=torch.float)  
x#like,模仿创建

tensor([-0.6330, -0.1256])

In [10]:
x.size()

torch.Size([2])

In [11]:
y = torch.rand(2)
y

tensor([0.7011, 0.9196])

In [12]:
z=torch.empty(2)
torch.add(x,y,out=z)#提供一个输出tensor 作为参数
z

tensor([0.0682, 0.7940])

In [13]:
y.add_(x)
y#in-place,带前缀'_'

tensor([0.0682, 0.7940])

In [14]:
x = torch.rand(5, 3)
x

tensor([[0.9252, 0.5161, 0.2422],
        [0.8171, 0.8149, 0.7978],
        [0.4486, 0.0847, 0.9329],
        [0.7109, 0.2350, 0.8202],
        [0.8438, 0.0503, 0.1604]])

In [15]:
x[:,1]

tensor([0.5161, 0.8149, 0.0847, 0.2350, 0.0503])

In [16]:
y=torch.randn(5,3)#正态分布
y

tensor([[ 1.0956,  1.2923, -1.1611],
        [ 0.6489,  0.4978, -0.3805],
        [ 0.4044, -0.2451,  0.8084],
        [-0.4620, -0.9358, -0.3865],
        [-0.5194,  1.1177,  1.8298]])

In [17]:
x.copy_(y)
x

tensor([[ 1.0956,  1.2923, -1.1611],
        [ 0.6489,  0.4978, -0.3805],
        [ 0.4044, -0.2451,  0.8084],
        [-0.4620, -0.9358, -0.3865],
        [-0.5194,  1.1177,  1.8298]])

In [18]:
x.view(3,5)#改维(不改变实际大小)

tensor([[ 1.0956,  1.2923, -1.1611,  0.6489,  0.4978],
        [-0.3805,  0.4044, -0.2451,  0.8084, -0.4620],
        [-0.9358, -0.3865, -0.5194,  1.1177,  1.8298]])

In [19]:
x[1,1].item()#获取值

0.49779388308525085

In [20]:
a=[i for i in range(1,17)]
t=torch.tensor(a).reshape(4,4)#use tensor 来创建
t

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [21]:
t1=torch.arange(1,17).reshape(4,4)
t1#use arange

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [22]:
#合并,传入一个元组
torch.cat((t,t1),dim=0),torch.cat((t,t1),dim=1)#0->行增多
#dim方向上的拼接

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),
 tensor([[ 1,  2,  3,  4,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  5,  6,  7,  8],
         [ 9, 10, 11, 12,  9, 10, 11, 12],
         [13, 14, 15, 16, 13, 14, 15, 16]]))

In [23]:
t==t1#按元素判断

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [24]:
t.sum().item()

136

In [25]:
#一个元素[1,2]
t[1,2]


tensor(7)

在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作

In [26]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [27]:
a+b#复制行和列使得维度相同

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [28]:
#切片
t[-1,:]#一行[1,:] (列为:)一列同理

tensor([13, 14, 15, 16])

In [29]:
#子区域
t[1:3,1:3]#左闭右开

tensor([[ 6,  7],
        [10, 11]])

In [30]:
#批量赋值
t[0:2,:]=1
t

tensor([[ 1,  1,  1,  1],
        [ 1,  1,  1,  1],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

\begin{bmatrix}
  \underline{1}& 1 &\underline{1}  &1 \\
  1&  1&1  & 1\\
  9& 10 &11  &12 \\
\underline{13}  & 14 & \underline{15} &16
\end{bmatrix}

In [31]:
#use::指定步长
t[::3,::2]

tensor([[ 1,  1],
        [13, 15]])

In [32]:
int(torch.rand(1)*10)#强制类型转换

8

In [33]:
before=id(t)
t+=t1
id(t)==before#原址操作，不改变id

True