In [1]:
import torch

A=torch.arange(1,17,dtype=torch.float32).reshape(4,4)
A

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [2]:
A.T

tensor([[ 1.,  5.,  9., 13.],
        [ 2.,  6., 10., 14.],
        [ 3.,  7., 11., 15.],
        [ 4.,  8., 12., 16.]])

In [3]:
#三维
B=torch.arange(24).reshape(2,3,4)
B

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [4]:
D=A.clone()#重新分配地址
C=A
C[0,0]=10
A[0,0]#只是浅层拷贝

tensor(10.)

In [5]:
D

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

$\text{Hadamard Product} $ : $A\odot B$

In [6]:
A*C#不常用

tensor([[100.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])

In [7]:
2+A,2*A#所有元素

(tensor([[12.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10.],
         [11., 12., 13., 14.],
         [15., 16., 17., 18.]]),
 tensor([[20.,  4.,  6.,  8.],
         [10., 12., 14., 16.],
         [18., 20., 22., 24.],
         [26., 28., 30., 32.]]))

$$a'_{np}=\sum_{i=1}^m a_{mnp}$$

In [8]:
B,B.shape,B.sum(axis=0),B.sum(axis=0).shape
#相同位置的相加将某一维合并

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [9]:
B.sum(axis=0,keepdims=True).shape#保留维度维1

torch.Size([1, 3, 4])

In [10]:
#number elements
A.numel()

16

In [11]:
# 累加求和
B.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]])

In [12]:
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4)
z=torch.dot(x,y)
z

tensor(6.)

In [13]:
torch.mv(A,x)#matrix-vector multiplication

tensor([20., 44., 68., 92.])

In [14]:
torch.mm(A,C)

tensor([[189., 118., 137., 156.],
        [247., 228., 254., 280.],
        [395., 356., 398., 440.],
        [543., 484., 542., 600.]])

In [15]:
A.norm()

tensor(39.9375)

$$||\vec{x}||_p=\sqrt[p]{\sum_{i=1}^n|x_i|}\\L_1范数$$

In [16]:
torch.abs(A).sum()

tensor(145.)

In [17]:
torch.cross(torch.tensor([3,2,-2]),torch.tensor([4,-3,1]))

tensor([ -4, -11, -17])

In [18]:
v=torch.tensor([[3.,2.,-2.]])
v*5/torch.norm(v)

tensor([[ 3.6380,  2.4254, -2.4254]])

In [25]:
torch.arccos(4/torch.sqrt(torch.tensor([442])))

tensor([1.3794])